version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    networks:
      - pritunl
    volumes:
      - mongo_data:/data/db
  pritunl:
    container_name: pritunl
    image: skoralex/pritunl:${VERSION}
    build: 
      context: .
      args:
        VERSION: ${VERSION}
        GO_VERSION: ${GO_VERSION}
    depends_on:
      - mongo
    networks:
      - pritunl
    volumes:
      - pritunl_data:/var/lib/pritunl
#      - ./pritunl.conf:/etc/pritunl.conf
    privileged: true

  pritunl-tests:
    container_name: pritunl-tests
    image: skoralex/pritunl-tests:${VERSION}
    build: 
      context: .
      dockerfile: Dockerfile-tests
      args:
        VERSION: ${VERSION}
        GO_VERSION: ${GO_VERSION}
    depends_on:
      - pritunl
    networks:
      - pritunl
#      - ./pritunl.conf:/etc/pritunl.conf
    privileged: true


networks:
  pritunl:
volumes:
  mongo_data:
  pritunl_data:

